"""
Regression tests for the v7.2 rule pack: AI governance, security
certification, and SLA response-time coverage (M_AI_OUTPUT_OWNERSHIP_01,
M_AI_HUMAN_REVIEW_01, M_SECURITY_CERT_MISSING_01, M_SLA_RESPONSE_TIME_01).

Each rule is REQUIRED_SECTION: only fires when its topic is genuinely in
scope for the document AND no protective language is found anywhere in
it — a document that never mentions the topic at all produces no finding
(the requirement doesn't apply), and a document that addresses the topic
correctly also produces no finding (see rules_engine.RuleClass docstring).
"""

import pytest
from rules_engine import RuleEngine


@pytest.fixture(scope="module")
def engine():
    return RuleEngine()


def _rule_ids(engine, text):
    return {f.rule_id for f in engine.analyze(text)["findings"]}


class TestAIOutputOwnership:
    def test_fires_when_ai_output_ownership_is_unaddressed(self, engine):
        text = (
            "This tool uses artificial intelligence to generate marketing content on behalf "
            "of Client under this Agreement."
        )
        assert "M_AI_OUTPUT_OWNERSHIP_01" in _rule_ids(engine, text)

    def test_does_not_fire_when_ownership_is_addressed(self, engine):
        text = (
            "Content generated using artificial intelligence under this Agreement shall be "
            "owned by Client."
        )
        assert "M_AI_OUTPUT_OWNERSHIP_01" not in _rule_ids(engine, text)

    def test_does_not_fire_when_topic_is_out_of_scope(self, engine):
        text = "This Agreement governs the sale of widgets between the parties."
        assert "M_AI_OUTPUT_OWNERSHIP_01" not in _rule_ids(engine, text)

    def test_does_not_falsely_flag_wellformed_ownership_language_as_adverse(self, engine):
        # Regression: an earlier version's chunked adverse-language pattern
        # matched ANY co-occurrence of an AI word and an ownership word,
        # regardless of polarity — so a well-drafted clause stating
        # ownership correctly still fired as if ownership were unaddressed.
        text = (
            "Any work product generated by artificial intelligence tools in the performance "
            "of the Services shall be owned by Client, and Client shall own all right, title, "
            "and interest therein."
        )
        assert "M_AI_OUTPUT_OWNERSHIP_01" not in _rule_ids(engine, text)


class TestAIHumanReview:
    def test_fires_when_no_human_review_is_required(self, engine):
        text = (
            "Recommendations generated by artificial intelligence may be relied upon by Client "
            "without human review."
        )
        assert "M_AI_HUMAN_REVIEW_01" in _rule_ids(engine, text)

    def test_does_not_fire_when_human_review_is_required(self, engine):
        text = (
            "Any output generated by artificial intelligence is subject to human review before "
            "it is relied upon or delivered to Client."
        )
        assert "M_AI_HUMAN_REVIEW_01" not in _rule_ids(engine, text)

    def test_does_not_fire_when_topic_is_out_of_scope(self, engine):
        text = "This Agreement governs the sale of widgets between the parties."
        assert "M_AI_HUMAN_REVIEW_01" not in _rule_ids(engine, text)


class TestSecurityCertification:
    def test_fires_when_no_certification_is_named(self, engine):
        text = (
            "Vendor shall implement reasonable information security measures to protect "
            "Customer Data from unauthorized access."
        )
        assert "M_SECURITY_CERT_MISSING_01" in _rule_ids(engine, text)

    def test_does_not_fire_when_soc2_is_named(self, engine):
        text = (
            "Vendor maintains information security measures and is SOC 2 Type II certified, "
            "with reports available upon request."
        )
        assert "M_SECURITY_CERT_MISSING_01" not in _rule_ids(engine, text)

    def test_does_not_fire_on_generic_safeguard_language_unrelated_to_infosec(self, engine):
        # Regression: a bare "safeguards" topic pattern matched "Buyer will
        # take all appropriate measures to safeguard the CONFIDENTIALITY
        # of..." in a real PSA fixture -- ordinary confidentiality-
        # protection prose, nothing to do with an information-security
        # posture at all. Narrowed to require the
        # administrative/physical/technical qualifier.
        text = (
            "Buyer will take all appropriate measures to safeguard the confidentiality of "
            "Seller's proprietary information and avoid disclosure to unauthorized persons."
        )
        assert "M_SECURITY_CERT_MISSING_01" not in _rule_ids(engine, text)

    def test_does_not_fire_when_topic_is_out_of_scope(self, engine):
        text = "This Agreement governs the sale of widgets between the parties."
        assert "M_SECURITY_CERT_MISSING_01" not in _rule_ids(engine, text)


class TestSLAResponseTime:
    def test_fires_when_no_response_time_is_specified(self, engine):
        text = "The Service Level Agreement guarantees 99.9% uptime for the Service each calendar month."
        assert "M_SLA_RESPONSE_TIME_01" in _rule_ids(engine, text)

    def test_does_not_fire_when_response_time_is_specified(self, engine):
        text = "The Service Level Agreement requires Vendor to respond within 4 hours of a reported incident."
        assert "M_SLA_RESPONSE_TIME_01" not in _rule_ids(engine, text)

    def test_does_not_fire_when_topic_is_out_of_scope(self, engine):
        text = "This Agreement governs the sale of widgets between the parties."
        assert "M_SLA_RESPONSE_TIME_01" not in _rule_ids(engine, text)


class TestOverallRiskUnaffected:
    def test_new_rules_are_additive_not_a_replacement_for_overall_risk(self, engine):
        text = (
            "The parties agree that either party may issue a press release regarding this "
            "Agreement without prior written consent."
        )
        result = engine.analyze(text)
        assert result["overall_risk"] == "high"
