"""Candidate 3 real-AI adversarial development corpus.

240 fresh cases (20 per adapter x 12 adapters), NOT copied from Candidate
1's 74-case corpus or Candidate 2's remediation tests. Ground truth
(`expected`) is authored here, before execution, and is NOT generated by
the same OpenAI provider being evaluated.

Each case's `family` is one of:
  LEE1..LEE10  -- the 10 mandatory "Critical Lee Test" categories
  NEGATED, UNRELATED, PARTY_ASYMMETRY, NUMERIC, BACKWARD_QUALIFIER,
  FORWARD_QUALIFIER, LONG_DISTANCE, CONTRADICTION, MISSING_CLAUSE,
  UNUSUAL_VALID_DRAFTING

`expected` is one of:
  YES_OPERATIVE, NO_NOT_OPERATIVE, YES_BUT_CONDITIONAL, YES_BUT_EXCEPTION,
  AMBIGUOUS, CROSS_REFERENCE_DEPENDENT, DEFINITION_DEPENDENT,
  MISSING_CLAUSE

This is a DEVELOPMENT/RED-TEAM corpus per the mission brief -- it will be
declared BURNED after the first run, per Section 13, and must never later
be represented as independent validation.
"""

CASES = []


def _add(adapter, family, lee, text, expected, policy=None, notes=""):
    CASES.append({
        "id": f"{adapter}-{len(CASES):03d}",
        "adapter": adapter,
        "family": family,
        "lee_category": lee,
        "text": text,
        "expected": expected,
        "policy": policy or {},
        "notes": notes,
    })


# =============================================================================
# 1. limitation_of_liability
# =============================================================================
_a = "limitation_of_liability"
_add(_a, "LEE1", 1,
     "14. Limitation of Liability. Except for breaches of Section 9 (Confidentiality), in no event shall either "
     "party's aggregate liability arising out of this Agreement exceed the total fees paid in the twelve (12) "
     "months preceding the claim.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Technology services agreements commonly cap aggregate liability at one times annual fees, "
     "reflecting standard industry risk allocation for engagements of this size.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if Vendor were found liable for a data breach, a typical agreement might limit damages to "
     "fees paid in the prior year -- illustrating how liability caps commonly operate in SaaS contracts.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties acknowledge that a liability cap has not yet been agreed and expect to negotiate specific "
     "limitation-of-liability terms, including the multiplier and any carve-outs, prior to execution.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Exhibit F (Vendor's Standard MSA Terms, referenced for informational purposes only and not incorporated "
     "herein) states: 'Provider's liability shall not exceed fees paid in the preceding six months.'",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "15. Cap on Liability. Vendor's aggregate liability shall not exceed two times the fees paid in the prior "
     "twelve months, provided that Customer has given Vendor written notice of the claim within ninety (90) days "
     "of discovering the underlying event.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "15. Cap on Liability. Vendor's aggregate liability shall not exceed one times the fees paid in the prior "
     "twelve months, except that this cap shall not apply to claims arising from Vendor's gross negligence or "
     "willful misconduct.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "15. Liability. The parties' liability under this Agreement shall be limited as set forth in the Order "
     "Form. Section 22 separately states that no limitation of liability shall apply to any claim, without "
     "clarifying which provision controls when an Order Form's cap and Section 22's blanket exclusion conflict.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "15. Limitation of Liability. Liability shall be capped as specified in Schedule C (Risk Allocation "
     "Terms) attached hereto.",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Schedule C is not included in the provided text.")
_add(_a, "LEE10", 10,
     "15. Limitation of Liability. Neither party's liability for Excluded Damages shall be capped under this "
     "Section. 'Excluded Damages' is defined in the Data Processing Addendum, which is not attached.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "15. Limitation of Liability. Nothing in this Agreement shall be construed to limit or cap either party's "
     "liability for any claim of any kind.",
     "NO_NOT_OPERATIVE",
     notes="Explicit negation of any cap -- must not be read as establishing a liability cap.")
_add(_a, "UNRELATED", None,
     "3. Term. This Agreement commences on the Effective Date and continues for an initial term of three years.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "15. Liability. Vendor's aggregate liability shall not exceed one times fees paid. Customer's liability "
     "to Vendor for any breach of the payment obligations in Section 6 shall be uncapped.",
     "YES_OPERATIVE",
     notes="Two directionally different caps -- must not be collapsed into one symmetric fact.")
_add(_a, "NUMERIC", None,
     "15. Liability. Vendor's aggregate liability shall not exceed the fees paid during the preceding two "
     "hundred and seventy (270) calendar days.",
     "YES_OPERATIVE",
     notes="Spelled-out compound number + explicit calendar-day unit.")
_add(_a, "BACKWARD_QUALIFIER", None,
     "15. Liability. Vendor's aggregate liability shall not exceed two times the fees paid in the prior twelve "
     "months.\n\n22. Notwithstanding Section 15, the cap described therein shall not apply to any claim arising "
     "from a breach of Section 9 (Confidentiality).",
     "YES_BUT_EXCEPTION",
     notes="Exception stated in a LATER section referring back to Section 15.")
_add(_a, "FORWARD_QUALIFIER", None,
     "15. Liability. Subject to Section 22, Vendor's aggregate liability shall not exceed one times fees paid "
     "in the prior twelve months.\n\n22. Carve-Outs. The cap in Section 15 shall not apply to claims arising "
     "from Vendor's indemnification obligations under Section 12.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "15. Liability. Vendor's aggregate liability shall not exceed one times the fees paid in the prior twelve "
     "months.\n\n[... sixteen unrelated sections on IP, confidentiality, termination, and boilerplate omitted "
     "for this excerpt ...]\n\n31. Miscellaneous Carve-Out. For the avoidance of doubt, the cap referenced in "
     "Section 15 above does not apply to breaches of the confidentiality obligations in this Agreement.",
     "YES_BUT_EXCEPTION")
_add(_a, "CONTRADICTION", None,
     "15. Liability. Vendor's aggregate liability shall not exceed one times the fees paid in the prior twelve "
     "months. 16. For clarity, Vendor's liability under this Agreement shall be unlimited and Section 15 shall "
     "not apply.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "9. Confidentiality. Each party shall protect the other's Confidential Information using reasonable care.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "15. Risk Ceiling. Come what may, and regardless of the theory of recovery pled, the most either party "
     "will ever be on the hook for under this Agreement is a sum equal to what Customer actually paid Vendor "
     "in the year before the claim arose.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing outside standard 'liability shall not exceed' regex vocabulary.")

# =============================================================================
# 2. indemnification
# =============================================================================
_a = "indemnification"
_add(_a, "LEE1", 1,
     "12. Indemnification. Vendor shall indemnify, defend, and hold harmless Customer from and against any "
     "third-party claims arising from Vendor's gross negligence or willful misconduct.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. It is standard practice for a services vendor to indemnify its customer against third-party "
     "IP infringement claims arising from the vendor's own deliverables.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "Suppose Vendor were obligated to indemnify Customer for claims arising from a data breach -- this "
     "illustrates the kind of risk-transfer clause common in this industry.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties have not yet finalized the scope of indemnification and expect to negotiate specific "
     "triggers, caps, and defense-control terms before signing.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's internal risk policy manual states, for reference only: 'Vendor shall indemnify clients against "
     "IP claims.' This manual is not part of this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "12. Indemnification. Vendor shall indemnify Customer against third-party IP infringement claims, "
     "provided that Customer promptly notifies Vendor in writing of any such claim within thirty (30) days.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "12. Indemnification. Vendor shall indemnify Customer against third-party claims arising from Vendor's "
     "products, except to the extent such claims arise from Customer's unauthorized modification of the "
     "products.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "12. Indemnification. Vendor shall indemnify Customer for claims 'arising from the Services.' Section 1 "
     "defines 'Services' broadly to include consulting, while Section 4 describes the Services narrowly as "
     "software licensing only, without reconciling which definition governs this Section.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "12. Indemnification. Vendor's indemnification obligations are subject to the procedures set forth in "
     "Exhibit D (Claims Handling Procedures).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Exhibit D not included.")
_add(_a, "LEE10", 10,
     "12. Indemnification. Vendor shall indemnify Customer for any 'Third-Party IP Claim.' That term is defined "
     "in the Master Terms document, which is referenced but not attached here.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "12. Indemnification. Vendor shall have no obligation whatsoever to indemnify, defend, or hold harmless "
     "Customer for any claim of any kind arising under this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "5. Invoicing. Vendor shall issue invoices monthly in arrears, itemized by service line.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "12. Indemnification. Vendor shall indemnify Customer against IP infringement claims arising from the "
     "Services. Customer shall indemnify Vendor only against claims arising from Customer-supplied content, "
     "and only where Customer had actual knowledge of the infringement.",
     "YES_OPERATIVE",
     notes="Customer's reciprocal obligation carries an actual-knowledge qualifier Vendor's does not.")
_add(_a, "NUMERIC", None,
     "12. Indemnification. Customer must provide notice of a claim within fifteen (15) business days of "
     "discovery for Vendor's indemnification obligation to apply.",
     "YES_BUT_CONDITIONAL",
     notes="Business days, not calendar days -- must not be silently treated as equivalent to 15 calendar days.")
_add(_a, "BACKWARD_QUALIFIER", None,
     "12. Indemnification. Vendor shall indemnify Customer against third-party IP claims arising from the "
     "Services.\n\n19. Notwithstanding Section 12, Vendor's indemnification obligation shall not apply to "
     "claims arising from Customer's combination of the Services with non-Vendor products.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "12. Indemnification. Subject to Section 18, Vendor shall indemnify Customer against third-party IP "
     "claims.\n\n18. Indemnification Exclusions. The obligation in Section 12 excludes claims arising from "
     "open-source components identified in Exhibit A.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "12. Indemnification. Vendor shall indemnify Customer against third-party IP claims arising from the "
     "Services.\n\n[... twenty unrelated sections omitted ...]\n\n41. General Provisions. Section 12's "
     "indemnification obligation is capped at the total fees paid under this Agreement.",
     "YES_BUT_CONDITIONAL",
     notes="A monetary cap is itself a material qualifier on the obligation, found far from Section 12.")
_add(_a, "CONTRADICTION", None,
     "12. Indemnification. Vendor shall indemnify Customer against all third-party claims without limitation. "
     "13. For the avoidance of doubt, Vendor shall have no indemnification obligations under this Agreement.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "9. Confidentiality. Each party shall protect the other's Confidential Information using reasonable care.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "12. Risk Transfer. If a third party comes after Customer because of something Vendor did wrong in "
     "delivering the Services, Vendor will step in, defend that claim, and cover Customer's resulting losses.",
     "YES_OPERATIVE",
     notes="Colloquial risk-transfer language without the word 'indemnify'.")

# =============================================================================
# 3. confidentiality
# =============================================================================
_a = "confidentiality"
_add(_a, "LEE1", 1,
     "8. Confidentiality. Each party shall protect the other's Confidential Information using reasonable care "
     "and shall not disclose it to third parties without prior written consent.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Confidentiality obligations are a standard feature of commercial agreements, typically "
     "requiring each party to protect the other's proprietary information.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For instance, if Vendor were required to protect Customer's trade secrets, it would typically do so for "
     "a period of three to five years after termination -- illustrating common confidentiality durations.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties intend to negotiate mutual confidentiality terms, including duration and permitted "
     "disclosures, as part of finalizing this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Per Vendor's standard NDA template (not executed and not part of this Agreement): 'Recipient shall hold "
     "Discloser's information in strict confidence for five years.'",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "8. Confidentiality. Vendor shall protect Customer's Confidential Information for five years, provided "
     "that Customer has clearly marked such information as 'Confidential' at the time of disclosure.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "8. Confidentiality. Each party shall protect the other's Confidential Information, except information "
     "that is independently developed without reference to the disclosing party's information.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "8. Confidentiality. Vendor shall protect 'Proprietary Data' disclosed by Customer. Section 1 defines "
     "'Proprietary Data' narrowly as pricing information, while Section 8.3 refers to it as covering all "
     "business information broadly, without reconciling the two.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "8. Confidentiality. The scope of protected information is as set forth in Schedule B (Confidential "
     "Information Categories).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Schedule B not included.")
_add(_a, "LEE10", 10,
     "8. Confidentiality. Vendor shall protect Customer's 'Restricted Data' for the Protection Period. Both "
     "terms are defined in Appendix 1, which is not attached.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "8. Confidentiality. Nothing in this Agreement obligates either party to keep the other's information "
     "confidential.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "4. Fees. Customer shall pay Vendor the fees set forth in the Order Form.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "8. Confidentiality. Vendor shall protect Customer's Confidential Information for five years using "
     "reasonable care. Customer shall protect Vendor's Confidential Information indefinitely using the "
     "highest degree of care available in the industry.",
     "YES_OPERATIVE",
     notes="Asymmetric duration/care standard split across two sentences -- must not be treated as symmetric.")
_add(_a, "NUMERIC", None,
     "8. Confidentiality. Vendor's confidentiality obligations survive for thirty-six (36) months following "
     "termination of this Agreement.",
     "YES_OPERATIVE",
     notes="Spelled-plus-digit compound duration.")
_add(_a, "BACKWARD_QUALIFIER", None,
     "8. Confidentiality. Vendor shall protect Customer's Confidential Information for five years.\n\n14. "
     "Notwithstanding Section 8, information that becomes publicly available through no fault of Vendor is "
     "excluded from the confidentiality obligation.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "8. Confidentiality. Subject to the exclusions in Section 8.5, Vendor shall protect Customer's "
     "Confidential Information for five years.\n\n8.5 Exclusions. The obligation above does not apply to "
     "information Vendor can demonstrate was already in its possession prior to disclosure.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "8. Confidentiality. Vendor shall protect Customer's Confidential Information for five years.\n\n[... "
     "fifteen unrelated sections omitted ...]\n\n29. Survival. For the avoidance of doubt, the five-year "
     "period referenced in Section 8 is measured from the date of each individual disclosure, not from the "
     "termination of this Agreement.",
     "YES_BUT_CONDITIONAL",
     notes="A materially different start-date rule for the duration, found far from Section 8.")
_add(_a, "CONTRADICTION", None,
     "8. Confidentiality. Vendor shall protect Customer's Confidential Information in perpetuity. 8.2 For "
     "clarity, Vendor's confidentiality obligations expire three years after termination.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "4. Fees. Customer shall pay Vendor the fees set forth in the Order Form within thirty days of invoice.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "8. Keeping Things Quiet. Whatever either side learns about the other's business that isn't already "
     "public, they'll keep to themselves and won't go blabbing to competitors, for as long as five years after "
     "this deal ends.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing far outside standard confidentiality regex vocabulary.")

# =============================================================================
# 4. payment_terms
# =============================================================================
_a = "payment_terms"
_add(_a, "LEE1", 1,
     "6. Payment Terms. Customer shall pay all undisputed invoiced amounts within thirty (30) days of the "
     "invoice date.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Net-30 payment terms are the market standard for enterprise software agreements of this "
     "size.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if Customer were required to pay within 30 days, a 1.5% monthly late fee would typically "
     "apply to overdue amounts -- a common structure in SaaS contracts.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties will negotiate final payment terms, including net days and any early-payment discount, "
     "before the Order Form is executed.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard rate card (attached for reference only, not incorporated into this Agreement) states: "
     "'Payment due Net 15.'",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "6. Payment Terms. Customer shall pay invoiced amounts within forty-five (45) days, provided that Vendor "
     "has delivered a valid, itemized invoice reflecting services actually rendered.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "6. Payment Terms. Customer shall pay all invoiced amounts within thirty (30) days, except for amounts "
     "reasonably disputed in good faith, which may be withheld pending resolution.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "6. Payment Terms. Payment is due within the period stated in the Order Form. One Order Form section "
     "says 'Net 30' while another says 'due upon receipt,' without indicating which governs.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "6. Payment Terms. Late fees are calculated as set forth in Schedule E (Late Fee Schedule).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Schedule E not included.")
_add(_a, "LEE10", 10,
     "6. Payment Terms. Customer shall pay the 'Recurring Fee' within thirty days of each 'Billing Cycle.' "
     "Both terms are defined in the Order Form, which is not attached.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "6. Payment Terms. Customer shall have no obligation to make any payment under this Agreement until a "
     "separate written payment schedule is executed by both parties.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "10. Termination. Either party may terminate this Agreement for convenience upon sixty days' notice.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "6. Payment Terms. Customer shall pay Vendor within thirty days of invoice. Vendor shall issue any refund "
     "owed to Customer within ninety days of the refund becoming due.",
     "YES_OPERATIVE",
     notes="Different timeframes for the two directions of payment flow.")
_add(_a, "NUMERIC", None,
     "6. Payment Terms. Customer shall pay invoiced amounts within twenty (20) business days of the invoice "
     "date.",
     "YES_OPERATIVE",
     notes="Business days explicitly, not calendar days -- must not silently equate the two.")
_add(_a, "BACKWARD_QUALIFIER", None,
     "6. Payment Terms. Customer shall pay all invoiced amounts within thirty days.\n\n11. Notwithstanding "
     "Section 6, amounts disputed in writing within fifteen days of invoice may be withheld pending "
     "resolution.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "6. Payment Terms. Subject to Section 6.4, Customer shall pay invoiced amounts within thirty days.\n\n"
     "6.4 Setoff. Customer may reduce any payment under Section 6 by amounts Vendor owes Customer under a "
     "final judgment.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "6. Payment Terms. Customer shall pay invoiced amounts within thirty days.\n\n[... eighteen unrelated "
     "sections omitted ...]\n\n33. Miscellaneous. For clarity, the thirty-day period in Section 6 is measured "
     "from Customer's receipt of the invoice, not its issue date.",
     "YES_BUT_CONDITIONAL")
_add(_a, "CONTRADICTION", None,
     "6. Payment Terms. Customer shall pay within thirty days of invoice. 6.2 For the avoidance of doubt, "
     "payment is due immediately upon execution of this Agreement, not on any invoice-based schedule.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "10. Termination. Either party may terminate this Agreement for convenience upon sixty days' notice.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "6. Getting Paid. Customer agrees to settle up on Vendor's bills within a month of getting them, no "
     "excuses.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing; 'a month' as an informal synonym for thirty days.")

# =============================================================================
# 5. ip_ownership
# =============================================================================
_a = "ip_ownership"
_add(_a, "LEE1", 1,
     "11. Intellectual Property. All work product created by Vendor specifically for Customer under this "
     "Agreement shall be owned exclusively by Customer upon full payment.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Custom software development agreements commonly assign work-product ownership to the "
     "paying customer upon completion of payment.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "Suppose Vendor built a custom reporting module for Customer -- in that scenario, ownership would "
     "typically transfer to Customer upon final payment, illustrating standard IP assignment practice.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties expect to negotiate IP ownership terms, including whether Vendor retains a license to reuse "
     "generic components, before finalizing this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard SOW template (for reference, not incorporated) states: 'All deliverables become "
     "Customer property upon payment.'",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "11. Intellectual Property. Work product shall be owned by Customer, provided that Customer has paid all "
     "fees associated with its creation in full.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "11. Intellectual Property. Work product shall be owned by Customer, except for Vendor's pre-existing "
     "background IP incorporated into the deliverables, which Vendor retains.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "11. Intellectual Property. Ownership of 'Deliverables' vests in Customer. Section 2 defines "
     "'Deliverables' as only the final report, while Section 11.3 refers to all 'work product,' a broader "
     "and undefined term, without reconciling the two.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "11. Intellectual Property. Ownership allocation for jointly developed components is as set forth in "
     "Schedule G (IP Allocation Matrix).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Schedule G not included.")
_add(_a, "LEE10", 10,
     "11. Intellectual Property. Vendor retains all rights to 'Pre-Existing Materials.' That term is defined "
     "in the Statement of Work, which is not attached.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "11. Intellectual Property. Nothing in this Agreement transfers, assigns, or licenses any intellectual "
     "property rights from either party to the other.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "7. Insurance. Vendor shall maintain Commercial General Liability insurance throughout the term.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "11. Intellectual Property. Vendor assigns all work product created under this Agreement to Customer. "
     "Customer grants Vendor only a limited, non-exclusive license to use Customer-supplied data solely to "
     "perform the Services.",
     "YES_OPERATIVE",
     notes="Full assignment one direction, limited license the other -- must not be conflated.")
_add(_a, "NUMERIC", None,
     "11. Intellectual Property. Vendor's license to use Customer's pre-existing materials is limited to a "
     "period of eighteen (18) months following termination.",
     "YES_OPERATIVE")
_add(_a, "BACKWARD_QUALIFIER", None,
     "11. Intellectual Property. All work product shall be owned by Customer.\n\n17. Notwithstanding Section "
     "11, Vendor retains a perpetual, royalty-free license to any general-purpose tools or libraries embedded "
     "in the work product.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "11. Intellectual Property. Subject to Section 11.6, all work product shall be owned by Customer.\n\n"
     "11.6 Vendor Retained Rights. Vendor retains ownership of any Vendor background IP used in creating the "
     "work product.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "11. Intellectual Property. All work product shall be owned by Customer.\n\n[... twenty unrelated "
     "sections omitted ...]\n\n38. Miscellaneous. For clarity, ownership under Section 11 does not include "
     "any open-source components identified in the applicable Statement of Work.",
     "YES_BUT_EXCEPTION")
_add(_a, "CONTRADICTION", None,
     "11. Intellectual Property. All work product is owned exclusively by Customer. 11.2 For the avoidance of "
     "doubt, Vendor retains all ownership rights in the work product and grants Customer only a license to "
     "use it.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "7. Insurance. Vendor shall maintain Commercial General Liability insurance throughout the term.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "11. Who Owns What. Once Customer's checks clear, anything Vendor builds specifically for this project "
     "belongs to Customer, lock, stock, and barrel.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing for full IP assignment conditioned on payment.")

# =============================================================================
# 6. insurance
# =============================================================================
_a = "insurance"
_add(_a, "LEE1", 1,
     "10. Insurance. Vendor shall maintain Commercial General Liability insurance with a minimum limit of "
     "$2,000,000 per occurrence throughout the term of this Agreement.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. It is common practice for a services vendor to carry Commercial General Liability insurance, "
     "though the specific coverage requirements for this engagement remain to be negotiated.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if Vendor were required to carry Cyber Liability insurance, a $1,000,000 limit would be "
     "typical for an engagement of this scope -- illustrating common coverage levels.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties have not yet agreed on specific insurance requirements and expect to finalize coverage "
     "types and limits before execution.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard insurance certificate template (attached for reference only) lists: 'CGL: "
     "$1,000,000/$2,000,000.'",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "10. Insurance. Vendor shall maintain Cyber Liability insurance with a minimum limit of $1,000,000, "
     "provided that such coverage is commercially available at commercially reasonable rates.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "10. Insurance. Vendor shall maintain Workers' Compensation insurance as required by law, except in "
     "jurisdictions where Vendor has no employees and no such requirement applies.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "10. Insurance. Vendor shall maintain insurance 'as required for the Services.' Section 2 describes the "
     "Services as consulting only, while Exhibit A describes on-site data-center work requiring far broader "
     "coverage, without reconciling which controls.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "10. Insurance. Vendor shall maintain insurance coverage as set forth in Exhibit D (Insurance "
     "Requirements) attached hereto.",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Exhibit D not included.")
_add(_a, "LEE10", 10,
     "10. Insurance. Vendor shall maintain the 'Required Coverage.' That term is defined in the Master "
     "Services Agreement, which is not attached here.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "10. Insurance. The parties agree that Vendor shall have no obligation to maintain any insurance "
     "coverage under this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "13. Governing Law. This Agreement is governed by the laws of the State of Delaware.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "10. Insurance. Vendor shall maintain Commercial General Liability insurance with a $2,000,000 limit. "
     "Customer shall maintain only such insurance as is required by applicable law for its own operations.",
     "YES_OPERATIVE",
     notes="Vendor bears a specific, named requirement; Customer's obligation is only a generic legal-minimum.")
_add(_a, "NUMERIC", None,
     "10. Insurance. Vendor shall provide Customer with thirty (30) calendar days' advance written notice "
     "before any cancellation or material reduction of the required coverage.",
     "YES_OPERATIVE")
_add(_a, "BACKWARD_QUALIFIER", None,
     "10. Insurance. Vendor shall maintain Commercial General Liability insurance with a $2,000,000 "
     "limit.\n\n16. Notwithstanding Section 10, the CGL requirement shall be reduced to $1,000,000 for any "
     "period during which Vendor performs no on-site work.",
     "YES_BUT_CONDITIONAL")
_add(_a, "FORWARD_QUALIFIER", None,
     "10. Insurance. Subject to Section 10.5, Vendor shall maintain Commercial General Liability insurance "
     "with a $2,000,000 limit.\n\n10.5 Alternative Compliance. Vendor may satisfy Section 10 through a "
     "combination of primary and umbrella policies totaling the required limit.",
     "YES_OPERATIVE")
_add(_a, "LONG_DISTANCE", None,
     "10. Insurance. Vendor shall maintain Commercial General Liability insurance with a $2,000,000 "
     "limit.\n\n[... twenty unrelated sections omitted ...]\n\n39. Miscellaneous. For clarity, the coverage "
     "required by Section 10 must name Customer as an additional insured.",
     "YES_BUT_CONDITIONAL")
_add(_a, "CONTRADICTION", None,
     "10. Insurance. Vendor shall maintain Commercial General Liability insurance with a $2,000,000 limit. "
     "10.2 For clarity, no specific insurance limits are required under this Agreement beyond what applicable "
     "law mandates.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "13. Governing Law. This Agreement is governed by the laws of the State of Delaware.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "10. Coverage Vendor Must Carry. Vendor needs to keep at least two million dollars of general liability "
     "coverage in force the whole time this deal is running.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing for a CGL requirement.")

# =============================================================================
# 7. data_security
# =============================================================================
_a = "data_security"
_add(_a, "LEE1", 1,
     "11. Data Protection. Vendor shall notify Customer of any personal data breach within forty-eight (48) "
     "hours of becoming aware of it.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Vendors in this industry usually notify customers of a personal data breach within 72 "
     "hours, reflecting common data-protection practice.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if a personal data breach occurred, a typical processor agreement would require "
     "notification within 72 hours -- illustrating common breach-notification timing.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties intend to negotiate a specific breach-notification window and will finalize the number of "
     "hours before execution of this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's internal security policy (referenced for background only, not incorporated) states: 'Notify "
     "affected customers of any personal data breach within 24 hours.'",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "11. Data Protection. Vendor shall notify Customer of any personal data breach within seventy-two (72) "
     "hours, provided that Vendor has confirmed the breach affects Customer's data specifically.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "11. Data Protection. Vendor shall notify Customer of any personal data breach within 48 hours, except "
     "where a law enforcement agency has directed a delay in notification.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "11. Data Protection. Vendor shall notify Customer of a 'Security Incident' within 48 hours. Section 1 "
     "defines 'Security Incident' narrowly as unauthorized access to production databases, while Section "
     "11.4 refers broadly to 'any security event,' without reconciling the two.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "11. Data Protection. Breach notification and remediation procedures are as set forth in the Data "
     "Processing Addendum attached as Exhibit B.",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Exhibit B not included.")
_add(_a, "LEE10", 10,
     "11. Data Protection. Vendor shall notify Customer of any 'Personal Data Breach' as defined in the "
     "Data Processing Addendum, which is not attached here.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "11. Miscellaneous. Vendor shall have no obligation to notify Customer of any personal data breach "
     "under this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "6. Fees. Customer shall pay Vendor's invoices within thirty days of receipt.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "11. Data Protection. Vendor, as processor, shall notify Customer of any personal data breach within "
     "48 hours. Customer, as controller, shall notify the applicable supervisory authority within 72 hours "
     "of Vendor's notice.",
     "YES_OPERATIVE",
     notes="Different timeframes and different obligated roles (processor vs controller).")
_add(_a, "NUMERIC", None,
     "11. Data Protection. Vendor shall notify Customer of any personal data breach within three (3) business "
     "days of becoming aware of it.",
     "AMBIGUOUS",
     notes="Ambiguous unit (business days) -- must fail closed, not be silently converted to 72 hours.")
_add(_a, "BACKWARD_QUALIFIER", None,
     "11. Data Protection. Vendor shall notify Customer of any personal data breach within 48 hours.\n\n17. "
     "Notwithstanding Section 11, the 48-hour window described therein shall not begin to run until Vendor's "
     "designated Data Protection Officer has confirmed the breach involves personal data.",
     "YES_BUT_CONDITIONAL")
_add(_a, "FORWARD_QUALIFIER", None,
     "11. Data Protection. Subject to Section 11.6, Vendor shall notify Customer of any personal data breach "
     "within 48 hours.\n\n11.6 Delayed Notice. Vendor may delay notice under Section 11 where a government "
     "authority directs delay for law enforcement purposes.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "11. Data Protection. Vendor shall notify Customer of any personal data breach within 48 hours.\n\n[... "
     "twenty unrelated sections omitted ...]\n\n40. Miscellaneous. For clarity, the notice required by "
     "Section 11 must be delivered to Customer's designated security contact, not general notices address.",
     "YES_BUT_CONDITIONAL")
_add(_a, "CONTRADICTION", None,
     "11. Data Protection. Vendor shall notify Customer of any personal data breach within 48 hours. 11.3 For "
     "clarity, Vendor has no obligation to proactively notify Customer of security incidents absent a written "
     "request.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "6. Fees. Customer shall pay Vendor's invoices within thirty days of receipt.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "11. If Something Goes Wrong With the Data. Should Vendor discover that someone got into personal data "
     "they shouldn't have, Vendor will let Customer know within two days, tops.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing; 'two days' -- ambiguous whether business or calendar, still must ground as best it can or flag ambiguity.")

# =============================================================================
# 8. governing_law
# =============================================================================
_a = "governing_law"
_add(_a, "LEE1", 1,
     "16. Governing Law. This Agreement shall be governed by and construed in accordance with the laws of "
     "the State of Delaware, without regard to its conflict-of-laws principles.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Technology agreements between companies headquartered in different states commonly select "
     "Delaware law due to its well-developed body of commercial case law.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if the parties wanted a neutral governing law, they might select New York law -- "
     "illustrating a common choice for cross-border technology agreements.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties have not yet agreed on a governing law and expect to select one during final contract "
     "negotiations.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard template agreement (for reference only, not part of this Agreement) selects "
     "California law as its governing law.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "16. Governing Law. This Agreement shall be governed by the laws of the State of New York, provided that "
     "any dispute relating to intellectual property shall instead be governed by federal law.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "16. Governing Law. This Agreement shall be governed by the laws of the State of Texas, except that "
     "matters relating to data privacy shall be governed by the law of the jurisdiction where the affected "
     "individual resides.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "16. Governing Law. This Agreement is governed by the law specified in the Order Form. One Order Form "
     "section names Delaware while a separate cover page names California, without indicating which "
     "controls.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "16. Governing Law. The governing law for this Agreement is as designated in the Master Framework "
     "Agreement referenced in the recitals.",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Master Framework Agreement not included.")
_add(_a, "LEE10", 10,
     "16. Governing Law. This Agreement is governed by the law of the 'Vendor's Principal Jurisdiction,' as "
     "defined in the Corporate Structure Addendum, which is not attached.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "16. Governing Law. This Agreement does not designate any governing law; the parties reserve the "
     "question for future agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "9. Confidentiality. Each party shall protect the other's Confidential Information using reasonable care.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "16. Governing Law. Disputes initiated by Customer shall be governed by Delaware law. Disputes initiated "
     "by Vendor shall be governed by the law of Vendor's state of incorporation.",
     "AMBIGUOUS",
     notes="Governing law that depends on which party sues is itself a genuinely unusual/ambiguous structure worth flagging, not silently resolved to one law.")
_add(_a, "NUMERIC", None,
     "16. Governing Law. Any objection to venue under this Section must be raised within twenty (20) days of "
     "the filing of an action.",
     "YES_BUT_CONDITIONAL")
_add(_a, "BACKWARD_QUALIFIER", None,
     "16. Governing Law. This Agreement is governed by the laws of the State of Delaware.\n\n22. "
     "Notwithstanding Section 16, any dispute arising from the Data Processing Addendum shall be governed by "
     "the law of the European Union member state where Customer is established.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "16. Subject to Section 16.3, this Agreement is governed by the laws of the State of Delaware.\n\n16.3 "
     "Exception. Consumer-protection claims, if any, shall instead be governed by the law of the consumer's "
     "state of residence.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "16. Governing Law. This Agreement is governed by the laws of the State of Delaware.\n\n[... twenty-two "
     "unrelated sections omitted ...]\n\n44. Miscellaneous. For clarity, the choice of Delaware law in "
     "Section 16 does not extend to any separate Data Processing Addendum executed by the parties.",
     "YES_BUT_EXCEPTION")
_add(_a, "CONTRADICTION", None,
     "16. Governing Law. This Agreement is governed by the laws of the State of Delaware. 16.2 For clarity, "
     "this Agreement is governed by the laws of the State of California.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "9. Confidentiality. Each party shall protect the other's Confidential Information using reasonable care.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "16. Whose Rules Apply. If push comes to shove and this deal ends up in court, Delaware's rules are the "
     "ones that'll apply, not wherever either of us happens to be sitting.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing for a governing-law clause.")

# =============================================================================
# 9. termination
# =============================================================================
_a = "termination"
_add(_a, "LEE1", 1,
     "18. Termination. Either party may terminate this Agreement for convenience upon sixty (60) days' "
     "prior written notice to the other party.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. It is standard practice for commercial services agreements to permit termination for "
     "convenience on 30 to 90 days' notice, depending on contract value.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if either party wanted to exit early, a typical clause would allow termination on 60 "
     "days' notice -- illustrating common termination-for-convenience structures.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties have not yet agreed on termination notice periods and expect to negotiate this term before "
     "signing.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard MSA template (for reference only) allows termination for convenience on 90 days' "
     "notice.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "18. Termination. Either party may terminate this Agreement for convenience upon sixty (60) days' "
     "notice, provided that Customer has paid all outstanding invoices as of the termination date.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "18. Termination. Either party may terminate for convenience upon 60 days' notice, except that Customer "
     "may not terminate for convenience during the first twelve months of the Initial Term.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "18. Termination. Either party may terminate 'as provided in the Order Form.' One Order Form provision "
     "allows termination on 30 days' notice; a separate cover sheet says termination requires 12 months' "
     "notice, without reconciling the two.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "18. Termination. Termination-for-cause procedures are as set forth in Schedule H (Default and Cure "
     "Procedures).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Schedule H not included.")
_add(_a, "LEE10", 10,
     "18. Termination. Either party may terminate upon a 'Material Breach' that remains uncured. 'Material "
     "Breach' is defined in the Master Agreement, which is not attached here.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "18. Termination. Neither party shall have any right to terminate this Agreement for convenience during "
     "the Initial Term.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "6. Payment Terms. Customer shall pay all invoices within thirty days of receipt.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "18. Termination. Customer may terminate this Agreement for convenience upon thirty days' notice. "
     "Vendor may terminate this Agreement for convenience only upon twelve months' notice and only after the "
     "Initial Term.",
     "YES_OPERATIVE",
     notes="Highly asymmetric termination rights -- must not be treated as mutual/symmetric.")
_add(_a, "NUMERIC", None,
     "18. Termination. Either party may terminate for convenience upon ninety (90) calendar days' prior "
     "written notice.",
     "YES_OPERATIVE")
_add(_a, "BACKWARD_QUALIFIER", None,
     "18. Termination. Either party may terminate for convenience upon sixty days' notice.\n\n24. "
     "Notwithstanding Section 18, Customer may not exercise the termination right described therein unless "
     "all outstanding fees have been paid in full.",
     "YES_BUT_CONDITIONAL")
_add(_a, "FORWARD_QUALIFIER", None,
     "18. Subject to Section 18.4, either party may terminate for convenience upon sixty days' notice.\n\n"
     "18.4 Minimum Term. The termination right in Section 18 may not be exercised before the end of the "
     "twelve-month Initial Term.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "18. Termination. Either party may terminate for convenience upon sixty days' notice.\n\n[... "
     "twenty-five unrelated sections omitted ...]\n\n47. Miscellaneous. For clarity, notice under Section 18 "
     "must be delivered in writing to the addresses specified in the Order Form, not by email alone.",
     "YES_BUT_CONDITIONAL")
_add(_a, "CONTRADICTION", None,
     "18. Termination. Either party may terminate for convenience upon sixty days' notice. 18.2 For clarity, "
     "this Agreement may not be terminated for convenience by either party under any circumstances.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "6. Payment Terms. Customer shall pay all invoices within thirty days of receipt.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "18. Walking Away. If either of us just isn't feeling this deal anymore, we can call it off, no reason "
     "needed, as long as we give the other side two months' heads-up first.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing; 'two months' as an informal synonym for sixty days.")

# =============================================================================
# 10. warranties
# =============================================================================
_a = "warranties"
_add(_a, "LEE1", 1,
     "13. Warranties. Vendor warrants that the Services will be performed in a professional and workmanlike "
     "manner consistent with generally accepted industry standards.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Services agreements typically include a warranty that the vendor will perform in a "
     "professional and workmanlike manner.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if a vendor were required to warrant its work, a standard clause might state that "
     "services will be performed in a professional manner -- illustrating a common warranty structure.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties have not yet finalized the warranty language and expect to negotiate the scope of any "
     "performance warranty before signing.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard SOW template (for reference only, not part of this Agreement) states: 'Vendor "
     "warrants professional and workmanlike performance.'",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "13. Warranties. Vendor warrants that the Services will conform to the specifications in the Statement "
     "of Work, provided that Customer has not materially altered the specifications after execution.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "13. Warranties. Vendor warrants the Services will be free of material defects for ninety days, except "
     "for defects caused by Customer's misuse or unauthorized modification.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "13. Warranties. Vendor warrants the 'Deliverables' will conform to specifications. Section 2 defines "
     "'Deliverables' as the final report only, while Section 13.2 refers broadly to 'all work product,' "
     "without reconciling the two.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "13. Warranties. Vendor's performance warranties are as further specified in Exhibit E (Service "
     "Standards).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Exhibit E not included.")
_add(_a, "LEE10", 10,
     "13. Warranties. Vendor warrants the Services will meet the 'Acceptance Criteria' defined in the "
     "Statement of Work, which is not attached here.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "13. Warranties. VENDOR MAKES NO WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, REGARDING THE SERVICES, "
     "AND EXPRESSLY DISCLAIMS ALL WARRANTIES INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
     "NO_NOT_OPERATIVE",
     notes="Blanket disclaimer -- must not be read as establishing an affirmative warranty.")
_add(_a, "UNRELATED", None,
     "17. Notices. All notices under this Agreement shall be in writing and delivered by certified mail.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "13. Warranties. Vendor warrants the Services will be performed in a professional and workmanlike "
     "manner. Customer warrants only that it has the authority to enter into this Agreement.",
     "YES_OPERATIVE",
     notes="Vendor's performance warranty is substantive; Customer's warranty is a bare authority representation.")
_add(_a, "NUMERIC", None,
     "13. Warranties. Vendor warrants the Services will be free of material defects for a period of one "
     "hundred eighty (180) days following delivery.",
     "YES_OPERATIVE")
_add(_a, "BACKWARD_QUALIFIER", None,
     "13. Warranties. Vendor warrants the Services will be performed in a professional and workmanlike "
     "manner.\n\n19. Notwithstanding Section 13, this warranty does not extend to any Services performed on "
     "an expedited basis at Customer's request.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "13. Subject to Section 13.5, Vendor warrants the Services will conform to the Statement of Work.\n\n"
     "13.5 Sole Remedy. Customer's sole remedy for breach of the warranty in Section 13 is re-performance of "
     "the nonconforming Services.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LONG_DISTANCE", None,
     "13. Warranties. Vendor warrants the Services will be performed in a professional and workmanlike "
     "manner.\n\n[... twenty unrelated sections omitted ...]\n\n42. Miscellaneous. For clarity, the warranty "
     "in Section 13 does not cover any Services identified in the Statement of Work as 'best-efforts only.'",
     "YES_BUT_EXCEPTION")
_add(_a, "CONTRADICTION", None,
     "13. Warranties. Vendor warrants the Services will be free of material defects. 13.2 For clarity, "
     "Vendor makes no warranty regarding the quality or defect-free status of the Services.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "17. Notices. All notices under this Agreement shall be in writing and delivered by certified mail.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "13. Our Promise on Quality. Vendor's going to do this work right, the way any solid outfit in this line "
     "of business would, no cut corners.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing for a professional/workmanlike performance warranty.")

# =============================================================================
# 11. sla
# =============================================================================
_a = "sla"
_add(_a, "LEE1", 1,
     "14. Service Level. The Service shall maintain 99.9% uptime, measured monthly, and Vendor shall provide "
     "service credits for any shortfall as set forth below.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. SaaS agreements typically commit to 99.9% uptime with service credits for shortfalls, "
     "reflecting standard industry SLA practice.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if a vendor committed to an SLA, 99.9% uptime with monthly measurement would be a typical "
     "target -- illustrating common service-level structures.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties have not yet negotiated specific service levels and expect to finalize the uptime "
     "commitment and credit structure before execution.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard SLA template (attached for reference only, not incorporated) commits to 99.5% "
     "uptime.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "14. Service Level. The Service shall maintain 99.9% uptime, provided that scheduled maintenance windows "
     "of up to four hours per month, with 48 hours' advance notice, are excluded from the calculation.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "14. Service Level. The Service shall maintain 99.9% uptime, except for downtime caused by Customer's "
     "own network or infrastructure failures.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "14. Service Level. The Service shall maintain uptime 'as specified for the Production Environment.' "
     "Section 1 defines 'Production Environment' as the primary data center only, while Section 14.3 refers "
     "to 'all environments,' without reconciling which controls.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "14. Service Level. Uptime commitments and service credit calculations are as set forth in Exhibit C "
     "(Service Level Schedule).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Exhibit C not included.")
_add(_a, "LEE10", 10,
     "14. Service Level. The Service shall maintain uptime as measured against the 'Availability Standard.' "
     "That term is defined in the Order Form, which is not attached here.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "14. Service Level. Vendor makes no uptime commitment of any kind and shall have no obligation to "
     "provide service credits under this Agreement.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "20. Assignment. Neither party may assign this Agreement without the other's prior written consent.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "14. Service Level. Vendor shall maintain 99.9% uptime and provide service credits for shortfalls. "
     "Customer's sole obligation related to the SLA is to report suspected downtime through Vendor's support "
     "portal within 24 hours.",
     "YES_OPERATIVE",
     notes="Substantive Vendor commitment paired with a minor, purely procedural Customer obligation.")
_add(_a, "NUMERIC", None,
     "14. Service Level. Scheduled maintenance windows of up to six (6) hours per calendar month are excluded "
     "from the uptime calculation, provided Vendor gives at least forty-eight (48) hours' notice.",
     "YES_BUT_CONDITIONAL")
_add(_a, "BACKWARD_QUALIFIER", None,
     "14. Service Level. The Service shall maintain 99.9% uptime.\n\n20. Notwithstanding Section 14, the "
     "uptime commitment described therein does not apply during the first thirty days following go-live.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "14. Subject to Section 14.6, the Service shall maintain 99.9% uptime.\n\n14.6 Force Majeure. The uptime "
     "commitment in Section 14 is suspended during any event described in Section 25 (Force Majeure).",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "14. Service Level. The Service shall maintain 99.9% uptime.\n\n[... twenty-three unrelated sections "
     "omitted ...]\n\n45. Miscellaneous. For clarity, the 99.9% uptime commitment in Section 14 excludes any "
     "beta or preview features made available to Customer at no charge.",
     "YES_BUT_EXCEPTION")
_add(_a, "CONTRADICTION", None,
     "14. Service Level. The Service shall maintain 99.9% uptime. 14.2 For clarity, Vendor does not guarantee "
     "any specific level of Service availability under this Agreement.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "20. Assignment. Neither party may assign this Agreement without the other's prior written consent.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "14. Keeping the Lights On. Vendor's going to keep this thing running north of 99.9% of the time, and "
     "if it dips below that, Customer gets money back per the schedule below.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing for an uptime commitment with service credits.")

# =============================================================================
# 12. assignment
# =============================================================================
_a = "assignment"
_add(_a, "LEE1", 1,
     "20. Assignment. Neither party may assign this Agreement, in whole or in part, without the prior "
     "written consent of the other party, such consent not to be unreasonably withheld.",
     "YES_OPERATIVE")
_add(_a, "LEE2", 2,
     "Background. Commercial agreements commonly restrict assignment without the counterparty's prior "
     "written consent, to protect against an unvetted successor stepping into the contract.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE3", 3,
     "For example, if Vendor were acquired, a typical assignment clause would require Customer's consent "
     "before the Agreement could transfer to the acquirer -- illustrating common assignment restrictions.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE4", 4,
     "The parties have not yet agreed on assignment restrictions and expect to finalize consent requirements "
     "before signing.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE5", 5,
     "Vendor's standard template (for reference only, not part of this Agreement) prohibits assignment "
     "without written consent.",
     "NO_NOT_OPERATIVE")
_add(_a, "LEE6", 6,
     "20. Assignment. Neither party may assign this Agreement without the other's prior written consent, "
     "provided that such consent shall not be required for an assignment to an Affiliate.",
     "YES_BUT_CONDITIONAL")
_add(_a, "LEE7", 7,
     "20. Assignment. Neither party may assign this Agreement without prior written consent, except that "
     "either party may assign this Agreement in connection with a merger, acquisition, or sale of "
     "substantially all of its assets.",
     "YES_BUT_EXCEPTION")
_add(_a, "LEE8", 8,
     "20. Assignment. Assignment requires consent 'except as otherwise permitted in the Order Form.' One "
     "Order Form section permits assignment to any subsidiary; a separate cover page requires consent for "
     "all assignments without exception, without reconciling the two.",
     "AMBIGUOUS")
_add(_a, "LEE9", 9,
     "20. Assignment. Permitted assignees and required notice procedures are as set forth in Schedule I "
     "(Assignment Procedures).",
     "CROSS_REFERENCE_DEPENDENT",
     notes="Schedule I not included.")
_add(_a, "LEE10", 10,
     "20. Assignment. Assignment to a 'Permitted Transferee' does not require consent. That term is defined "
     "in the Corporate Structure Addendum, which is not attached here.",
     "DEFINITION_DEPENDENT")
_add(_a, "NEGATED", None,
     "20. Assignment. This Agreement imposes no restriction on either party's ability to assign its rights "
     "or obligations to any third party.",
     "NO_NOT_OPERATIVE")
_add(_a, "UNRELATED", None,
     "14. Service Level. The Service shall maintain 99.9% uptime, measured monthly.",
     "NO_NOT_OPERATIVE")
_add(_a, "PARTY_ASYMMETRY", None,
     "20. Assignment. Vendor may assign this Agreement freely, including to any Affiliate or in connection "
     "with a change of control, without Customer's consent. Customer may not assign this Agreement under any "
     "circumstances without Vendor's prior written consent.",
     "YES_OPERATIVE",
     notes="Highly asymmetric assignment rights -- must not be treated as mutually restricted.")
_add(_a, "NUMERIC", None,
     "20. Assignment. A party seeking to assign this Agreement to an Affiliate shall provide the other party "
     "with fifteen (15) business days' advance written notice.",
     "YES_BUT_CONDITIONAL")
_add(_a, "BACKWARD_QUALIFIER", None,
     "20. Assignment. Neither party may assign this Agreement without prior written consent.\n\n26. "
     "Notwithstanding Section 20, an assignment to a successor in a merger or acquisition does not require "
     "the other party's consent, provided the successor agrees in writing to be bound by this Agreement.",
     "YES_BUT_EXCEPTION")
_add(_a, "FORWARD_QUALIFIER", None,
     "20. Subject to Section 20.4, neither party may assign this Agreement without prior written consent.\n\n"
     "20.4 Permitted Assignment. Either party may assign this Agreement to an Affiliate without consent, "
     "provided the assigning party remains liable for performance.",
     "YES_BUT_EXCEPTION")
_add(_a, "LONG_DISTANCE", None,
     "20. Assignment. Neither party may assign this Agreement without prior written consent.\n\n[... "
     "twenty-six unrelated sections omitted ...]\n\n48. Miscellaneous. For clarity, an assignment permitted "
     "under Section 20 does not relieve the assigning party of its payment obligations accrued prior to the "
     "assignment.",
     "YES_BUT_CONDITIONAL")
_add(_a, "CONTRADICTION", None,
     "20. Assignment. Neither party may assign this Agreement without the other's prior written consent. "
     "20.2 For clarity, either party may freely assign this Agreement to any third party without consent or "
     "notice.",
     "AMBIGUOUS")
_add(_a, "MISSING_CLAUSE", None,
     "14. Service Level. The Service shall maintain 99.9% uptime, measured monthly.",
     "MISSING_CLAUSE")
_add(_a, "UNUSUAL_VALID_DRAFTING", None,
     "20. Passing This Along. If either of us wants to hand this contract off to someone else, we need the "
     "other side's okay first, in writing, and they can't be unreasonable about giving it.",
     "YES_OPERATIVE",
     notes="Colloquial phrasing for a consent-required assignment restriction.")
