"""initial_schema

Revision ID: fc1a942c12af
Revises: 
Create Date: 2026-06-27 04:14:30.946566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1a942c12af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('monthly_limit', sa.Integer(), nullable=True),
    sa.Column('contracts_this_month', sa.Integer(), nullable=True),
    sa.Column('usage_reset_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_plan', 'users', ['plan'], unique=False)
    op.create_index('ix_users_subscription_status', 'users', ['subscription_status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('template_findings_json', sa.JSON(), nullable=True),
    sa.Column('template_risk', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_user_id'), 'playbooks', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('stripe_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('contract_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('overall_risk', sa.String(length=20), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('llm_result_json', sa.JSON(), nullable=True),
    sa.Column('rule_counts_json', sa.JSON(), nullable=True),
    sa.Column('rule_engine_version', sa.String(length=20), nullable=True),
    sa.Column('analysis_completed', sa.Boolean(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('deviations_json', sa.JSON(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_password_hash', sa.String(length=255), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('analysis_duration_ms', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_batch_id'), 'contracts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_contracts_share_token'), 'contracts', ['share_token'], unique=True)
    op.create_index('ix_contracts_user_created', 'contracts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.create_index('ix_contracts_user_risk', 'contracts', ['user_id', 'overall_risk'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_analysis_id'), 'analysis_jobs', ['analysis_id'], unique=True)
    op.create_index(op.f('ix_analysis_jobs_batch_id'), 'analysis_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_user_id'), 'analysis_jobs', ['user_id'], unique=False)
    op.create_index('ix_jobs_created_at', 'analysis_jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_status', 'analysis_jobs', ['status'], unique=False)
    op.create_index('ix_jobs_user_status', 'analysis_jobs', ['user_id', 'status'], unique=False)
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_cents', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_user_created', 'api_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index('ix_api_usage_user_created', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index('ix_jobs_user_status', table_name='analysis_jobs')
    op.drop_index('ix_jobs_status', table_name='analysis_jobs')
    op.drop_index('ix_jobs_created_at', table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_user_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_batch_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_analysis_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index('ix_contracts_user_risk', table_name='contracts')
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_index('ix_contracts_user_created', table_name='contracts')
    op.drop_index(op.f('ix_contracts_share_token'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_batch_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('stripe_events')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_playbooks_user_id'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_subscription_status', table_name='users')
    op.drop_index('ix_users_plan', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
