"""
The eight CSV/HTML deliverables TriageBench Live produces per run:
production_summary.html, production_failures.csv, workflow_statistics.csv,
performance_statistics.csv, browser_results.csv, security_results.csv,
production_regressions.csv, contract_results.csv.

This module writes the CSVs; production_summary.html (which includes the
Production Readiness Report) is generated by dashboard.py, and
production_regressions.csv by regression.py — both listed here in
generate_all's return value so callers get one place to check what was
produced.
"""
from __future__ import annotations

import csv
from pathlib import Path
from typing import Any, Dict, List

from . import aggregate as agg
from . import storage


def _write_csv(path: Path, rows: List[Dict[str, Any]], fieldnames: List[str]) -> None:
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def generate_all(
    run_id: str,
    contract_records: List[Dict[str, Any]],
    security_findings: List[Dict[str, Any]],
    failure_results: List[Dict[str, Any]],
    concurrency_results: List[Dict[str, Any]],
    browser_results: List[Dict[str, Any]],
) -> Dict[str, int]:
    out_dir = storage.config.run_dir(run_id) / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    counts: Dict[str, int] = {}

    # contract_results.csv — one row per contract's full journey
    contract_rows = []
    for rec in contract_records:
        m = rec.get("metrics", {})
        contract_rows.append({
            "contract_id_hint": rec.get("contract_id_hint"), "category": rec.get("category"),
            "company_name": rec.get("company_name"), "filename": rec.get("filename"),
            "live_contract_id": rec.get("live_contract_id"), "test_email": rec.get("test_email"),
            "overall_status": rec.get("overall_status"), "failures": ";".join(rec.get("failures") or []),
            "findings_count": m.get("findings_count"), "accepted": m.get("accepted"),
            "rejected": m.get("rejected"), "edited": m.get("edited"), "flagged": m.get("flagged"),
            "commented": m.get("commented"),
        })
    _write_csv(out_dir / "contract_results.csv", contract_rows, [
        "contract_id_hint", "category", "company_name", "filename", "live_contract_id", "test_email",
        "overall_status", "failures", "findings_count", "accepted", "rejected", "edited", "flagged", "commented",
    ])
    counts["contract_results.csv"] = len(contract_rows)

    # production_failures.csv — every non-pass contract, every failed
    # security check, every failed failure-injection/concurrency probe, in
    # one place someone can triage top to bottom.
    failure_rows = [
        {"source": "contract_workflow", "name": r["contract_id_hint"], "severity": "high",
         "detail": f"{r['overall_status']}: {r['failed_steps']} — {r['first_error'][:200]}"}
        for r in agg.compute_contract_failures(contract_records)
    ]
    failure_rows += [
        {"source": "security", "name": f["check"], "severity": f["severity"], "detail": f["detail"][:300]}
        for f in security_findings if not f.get("passed")
    ]
    failure_rows += [
        {"source": "failure_injection", "name": f["name"], "severity": f["severity"], "detail": f["detail"][:300]}
        for f in failure_results if not f.get("passed")
    ]
    failure_rows += [
        {"source": "concurrency", "name": c["name"], "severity": c["severity"], "detail": c["detail"][:300]}
        for c in concurrency_results if not c.get("passed")
    ]
    failure_rows += [
        {"source": "browser", "name": f"{b['browser']}:{s['name']}", "severity": "high", "detail": s.get("detail", "")[:300]}
        for b in browser_results if b.get("available")
        for s in b.get("steps", []) if s.get("status") in ("fail", "error")
    ]
    _write_csv(out_dir / "production_failures.csv", failure_rows, ["source", "name", "severity", "detail"])
    counts["production_failures.csv"] = len(failure_rows)

    # workflow_statistics.csv
    wf = agg.compute_workflow_statistics(contract_records)
    wf_rows = [{"metric": "contracts_processed", "value": wf["contracts_processed"]},
               {"metric": "pass_rate_pct", "value": wf["pass_rate_pct"]}]
    for status, n in wf["status_counts"].items():
        wf_rows.append({"metric": f"status_count_{status}", "value": n})
    for step, counts_by_status in wf["step_status_counts"].items():
        for status, n in counts_by_status.items():
            wf_rows.append({"metric": f"step_{step}_{status}", "value": n})
    for k, v in wf["decision_totals"].items():
        wf_rows.append({"metric": f"decision_total_{k}", "value": v})
    _write_csv(out_dir / "workflow_statistics.csv", wf_rows, ["metric", "value"])
    counts["workflow_statistics.csv"] = len(wf_rows)

    # performance_statistics.csv
    perf = agg.compute_performance_statistics(contract_records)
    perf_rows = [{"step": step, **vals} for step, vals in perf.items()]
    _write_csv(out_dir / "performance_statistics.csv", perf_rows, [
        "step", "count", "mean_ms", "median_ms", "p95_ms", "max_ms", "min_ms",
    ])
    counts["performance_statistics.csv"] = len(perf_rows)

    # browser_results.csv
    browser_rows = []
    for b in browser_results:
        for s in b.get("steps", []):
            browser_rows.append({
                "browser": b["browser"], "available": b.get("available"), "step": s["name"],
                "status": s["status"], "ms": s.get("ms"), "detail": s.get("detail", "")[:300],
            })
    _write_csv(out_dir / "browser_results.csv", browser_rows, ["browser", "available", "step", "status", "ms", "detail"])
    counts["browser_results.csv"] = len(browser_rows)

    # security_results.csv
    sec_rows = [
        {"check": f["check"], "passed": f["passed"], "severity": f["severity"], "detail": f["detail"][:400]}
        for f in security_findings
    ]
    _write_csv(out_dir / "security_results.csv", sec_rows, ["check", "passed", "severity", "detail"])
    counts["security_results.csv"] = len(sec_rows)

    # production_regressions.csv is written by regression.py — placeholder
    # kept present so the file always exists, even for a run with no
    # baseline yet.
    regression_path = out_dir / "production_regressions.csv"
    if not regression_path.exists():
        _write_csv(regression_path, [], ["kind", "name", "detail"])
    counts["production_regressions.csv"] = 0

    return counts
